classdef TestSubIndexReader < TestProxyReader
    methods
        function obj = TestSubIndexReader(name)
            R = MockReader;
            obj = obj@TestProxyReader(name, ...
                SubIndexReader(R, ...
                                1:R.getSizeC, ...
                                1:R.getSizeT, ...
                                1:R.getSizeZ ...
                ));
        end
    end
end
